framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'

    secret: '%env(APP_SECRET)%'
    csrf_protection: ~
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']

    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    php_errors:
        log: true
