version: '2'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eating_project
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  application:
    build: .
    ports:
      - "81:80"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
