# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        EatingBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: EatingBundle:User
                property: email
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~
            pattern:    ^/
            provider: our_db_provider
            logout_on_user_change: true
            logout:
                path: /logout
            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/user, roles: ROLE_USER }
         - { path: ^/recommendation, roles: ROLE_USER }
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
