services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EatingBundle\Controller\:
        resource: '../../Controller/'
        public: true

    service.file_uploader:
        class: EatingBundle\Service\FileUploader
        arguments: ['%file_directory%']

    event_listener.file_uploader:
        class: EatingBundle\EventListener\FileUploadListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
