services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EatingBundle\Controller\:
        resource: '../../Controller/'
        public: true

    EatingBundle\Service\FileUploader:
        public: true
        arguments: ['%file_directory%']

    EatingBundle\EventListener\FileUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
